id = "kratos"
name = "Kellton Kratos"
description = "The open source coding agent."
version = "1.1.6"
schema_version = 1
authors = ["Anomaly"]
repository = "https://github.com/anomalyco/kratos"

[agent_servers.kratos]
name = "Kellton Kratos"
icon = "./icons/kratos.svg"

[agent_servers.kratos.targets.darwin-aarch64]
archive = "https://github.com/anomalyco/kratos/releases/download/v1.1.6/kratos-darwin-arm64.zip"
cmd = "./kratos"
args = ["acp"]

[agent_servers.kratos.targets.darwin-x86_64]
archive = "https://github.com/anomalyco/kratos/releases/download/v1.1.6/kratos-darwin-x64.zip"
cmd = "./kratos"
args = ["acp"]

[agent_servers.kratos.targets.linux-aarch64]
archive = "https://github.com/anomalyco/kratos/releases/download/v1.1.6/kratos-linux-arm64.tar.gz"
cmd = "./kratos"
args = ["acp"]

[agent_servers.kratos.targets.linux-x86_64]
archive = "https://github.com/anomalyco/kratos/releases/download/v1.1.6/kratos-linux-x64.tar.gz"
cmd = "./kratos"
args = ["acp"]

[agent_servers.kratos.targets.windows-x86_64]
archive = "https://github.com/anomalyco/kratos/releases/download/v1.1.6/kratos-windows-x64.zip"
cmd = "./kratos.exe"
args = ["acp"]
